/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rmiproject;

import static org.junit.jupiter.api.Assertions.assertTrue;

import java.rmi.RemoteException;
import java.util.stream.IntStream;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class RequestReadLockTest {

    private RemoteStringArrayImpl remoteArray;

    @BeforeEach
    public void setUp() throws RemoteException {
        int capacity = 5;
        remoteArray = new RemoteStringArrayImpl(capacity);
        String[] initVals = { "a", "b", "c" };
        IntStream.range(0, initVals.length).forEach(i -> {
            try {
                remoteArray.insertArrayElement(i, initVals[i]);
            } catch (RemoteException e) {
                e.printStackTrace();
            }
        });

    }

    @Test
    void testLockAcquisitionSuccess() throws RemoteException {
        boolean result = remoteArray.requestReadLock(1, 123);
        assertTrue(result);
    }

    @Test
    public void testMultipleClientsReadingSameLock() throws RemoteException {

        boolean result1 = remoteArray.requestReadLock(4, 111);
        boolean result2 = remoteArray.requestReadLock(4, 222);

        assertTrue(result1);
        assertTrue(result2);
    }

}
